# Generated by Django 2.0.7 on 2018-07-11 17:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_auto_20180711_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(through='core.ProjectUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
